### ISSUE TITLE
I can't run the example code.

### ISSUE THREAD

**Issue by luiscarlos-gonzalez** [hokein/Automata.js#1]
Hi, I install via npm and try to execute the examples but it fails. I got the next error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'regparser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kentverger/Documentos/UPSLP/Compiladores/regexToNDA/index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

The example was: 

```
var regParser = require('regparser');

var parser = new regParser.RegParser('a*b');
var nfa = parser.parseToNFA();

nfa.toDotScript();
```

My node version is 0.10.33 and my operative system is Ubuntu 15.04

**Comment by luiscarlos-gonzalez** [comment]
There was an error on the example code n.n I update the readme file and make the pull request. 

Thanks a lot for this project :)

**Comment by hokein** [comment]
I close this since the PR has been merged.
